config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :menus do
    get :confirm, on: :member
    get :qr_code, on: :member
    resources :sections do
      patch :move, on: :member
      get :confirm, on: :member
      resources :items do
        patch :move, on: :member
        get :confirm, on: :member
      end
    end
  end
  resources :restaurants do
    get :confirm, on: :member
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :site
  
  unauthenticated do
    root "site#index"
  end

  authenticated :user do
    root "menus#index", as: :authenticated_root
  end
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :restaurant
  belongs_to :user
  has_many :sections, dependent: :destroy
  scope :all_except, ->(menu) { where.not(id: menu) }
  validates :title, presence: true
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :verify_restaurants, except: [:show]
  before_action :set_menu, only: [:edit, :update, :show, :destroy, :confirm, :qr_code]

  def index
  end

  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.new(menu_params)
    @menu.user_id = current_user.id

    if @menu.save
      set_published
      flash[:notice] = "Menu Created, add some sections!"
      redirect_to edit_menu_path(@menu)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    render layout: "menu"
  end

  def edit
  end

  def update
    if @menu.update(menu_params)
      set_published
      flash[:notice] = "Menu Updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @menu.destroy
      flash[:notice] = "Menu Removed."
    else
      flash[:notice] = "Unable to Remove Menu."
    end
  end

  def confirm
  end

  def qr_code
    send_data RQRCode::QRCode.new(menu_url(@menu)).as_png(size: 300), type: "image/png", disposition: "attachment"
  end

  private

  def verify_restaurants
    if current_user.restaurants.empty?
      redirect_to new_restaurant_path, flash: {notice: "You must create your restaurant first!"}
    end
  end

  def set_menu
    @menu = authorize Menu.find(params[:id])

    if @menu.nil?
      redirect_to root_path, flash: {notice: "Menu not found"}
    end
  end

  def set_published
    if @menu.published
      @menu.restaurant.menus.all_except(@menu).update_all(published: false)
    end
  end

  def menu_params
    params.require(:menu).permit(:title, :description, :restaurant_id, :published)
  end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/_address.html.erb
<h2 class="text-3xl font-bold leading-8 tracking-tight text-gray-900 sm:text-4xl"><%= @menu.restaurant.name%></h2>
<div class="mt-2 text-base text-gray-500">
  <p><%= @menu.restaurant.address %></p>
    <p class="mt-1"><%= @menu.restaurant.address2 %></p>
  <p class="mt-1"><%= @menu.restaurant.city %> <%= @menu.restaurant.state %>, <%= @menu.restaurant.zipcode %></p>
</div>

app/views/menus/_contacts.html.erb
<div class="flex-shrink-0">
  <%= content_tag(:span, :call, class: "material-symbols-outlined  text-gray-400") %>
</div>
<% if @menu.restaurant.phone.present? %>
  <div class="ml-3 text-base text-gray-500">
    <p><%= @menu.restaurant.phone%></p>
  </div>
<% end %>
</div>
<% if @menu.restaurant.email.present? %>
  <div class="mt-2 flex">
    <div class="flex-shrink-0">
      <%= content_tag(:span, :mail, class: "material-symbols-outlined  text-gray-400") %>
    </div>
    <div class="ml-3 text-base text-gray-500">
      <p><%= @menu.restaurant.email%></p>
    </div>
  </div>
<% end %>
<% if @menu.restaurant.twitter.present? %>
  <div class="mt-2 flex">
    <div class="flex-shrink-0">
      <%= inline_svg_tag "twitter.svg", class: 'h-6 w-6 stroke-white', alt: "Twitter" %>
    </div>
    <div class="ml-3 text-base text-gray-500">
      <p><%= @menu.restaurant.twitter%></p>
    </div>
  </div>
<% end %>
<% if @menu.restaurant.instagram.present? %>
  <div class="mt-2 flex">
    <div class="flex-shrink-0">
      <%= inline_svg_tag "instagram.svg", class: 'h-6 w-6 stroke-white', alt: "Instagram" %>
    </div>
    <div class="ml-3 text-base text-gray-500">
      <p><%= @menu.restaurant.instagram%></p>
    </div>
  </div>
<% end %>
<% if @menu.restaurant.facebook.present? %>
  <div class="mt-2 flex">
    <div class="flex-shrink-0">
      <%= inline_svg_tag "facebook.svg", class: 'h-6 w-6 stroke-white', alt: "Facebook" %>
    </div>
    <div class="ml-3 text-base text-gray-500">
      <p><%= @menu.restaurant.facebook%></p>
    </div>
  </div>
<% end %>

app/views/menus/_form.html.erb
<%= form_for @menu, builder: TailwindBuilder do |f| %>
  <div class="border-gray-100 border-b-2">
    <div class="mt-4 grid grid-cols-1 sm:grid-cols-2 mx-auto px-2 sm:divide-x divide-solid">
      <div class="p-4">
        <div>
          <h3 class="text-lg font-medium leading-6 text-gray-900">Menu Information</h3>
          <p class="mt-1 text-sm text-gray-500">Name the menu and associate it with one of your establishments.</p>
        </div>
        <%= render partial: 'shared/form_errors', locals: {f:f} %>
        <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
          <div class="sm:col-span-4">
            <%= f.label :title, "Menu Title" %>
            <%= f.tw_text_field :title, placeholder: "Main Menu", required: true %>
          </div>
          <div class="sm:col-span-4">
            <%= f.label :description %>
            <%= f.tw_text_field :description, placeholder: "" %>
          </div>
          <div class="sm:col-span-4">
            <%= f.label :restaurant,  class: "block text-sm font-medium text-gray-700" %>
            <%= f.collection_select :restaurant_id, current_user.restaurants, :id, :name,{}, {class: "block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"} %>
          </div>
          <div class="sm:col-span-6">
            <%= f.label :title, "Publish Menu" %>
            <p class="text-gray-500">All other menus for this restaurant will be unpublished.</p>
            <%= f.check_box :published  %>
          </div>
        </div>
      </div>
    </div>
    <div class="mt-4 p-5 flex justify-end">
      <%= f.submit "Save", class: "ml-3 inline-flex justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
    </div>
  </div>
<% end %>

app/views/menus/_header.html.erb
<section class="bg-gradient-to-r from-gray-800 to-gray-600 pb-24">
  <div class="mx-auto max-w-3xl px-4 sm:px-6 lg:max-w-7xl lg:px-8">
    <div class="relative sm:flex flex-wrap items-center justify-center lg:justify-between">
      <!-- Logo -->
      <div class="absolute left-0 flex-shrink-0 py-5 lg:static">
        <%= link_to root_path, class: "flex" do %>
          <%= inline_svg_tag "logo.svg", class: 'h-9 w-9 stroke-white', alt: "Menu Maker" %>
          <h3 class="ml-2 text-white text-2xl">Menu Maker</h3>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/menus/_hours.html.erb
<div class="flex">
  <div class="flex-shrink-0">
    <%= content_tag(:span, :schedule, class: "material-symbols-outlined  text-gray-400") %>
  </div>
  <div class="ml-3 w-full text-base text-gray-500">
    <% @menu.restaurant.business_hours.order(day: :asc).each do |day|%>
      <div class="flex justify-between">
        <%= Date::DAYNAMES[day.day] %>: 
        <div><%= day.hours %></div>
      </div>
    <% end %>
  </div>
</div>

app/views/menus/_menu.html.erb
<section aria-labelledby="profile-overview-title">
  <div class="overflow-hidden rounded-lg bg-white shadow">
    <div class="p-6">
      <h2 class="sr-only" id="menu-section"><%= @menu.title %></h2>
      <div class="max-w-xl">
        <h2 class="text-4xl font-bold tracking-tight text-gray-900 sm:text-5xl lg:text-6xl"><%= @menu.title %></h2>
        <p class="mx-auto mt-5 max-w-xl text-xl text-gray-500"><%= @menu.description %></p>
      </div>
      <% @menu.sections.order(position: :asc).each do |section|%>
        <div class="mt-8">
          <h3 class="text-lg font-medium">
            <span class="absolute inset-0" aria-hidden="true"></span>
            <%= section.title %>
          </h3>
          <p class="mt-2 text-sm text-gray-500"><%= section.description %></p>
          <%= render(ItemComponent.with_collection(section.items.order(position: :asc), show_controls: false, show_handle: false, show_upload: false))%>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/menus/confirm.html.erb
<%= render TurboModalComponent.new(title: "Are you sure?") do %>
  <div class="mt-2 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
    <div class="sm:col-span-4">Do you really want to delete:</div>
    <div class="sm:col-span-6">
      <h2 class="text-2xl text-gray-900"><%= @menu.title %></h2>
      <h3 class="text-lg text-gray-900"><%= @menu.restaurant.name %></h3>
      <p><%= @menu.restaurant.address %><%= @menu.restaurant.address2 %></p>
      <p><%= @menu.restaurant.city %> <%= @menu.restaurant.state %>, <%= @menu.restaurant.zipcode %></p>
    </div>
    <div class="sm:col-span-4">
      <div class="flex">
        <%= button_tag "Cancel", data: { action: "modal#hideModal" }, type: "button", class: "rounded-lg py-3 px-5 bg-blue-600 text-white" %>
        <%= button_to 'Delete', menu_path(@menu), class: "ml-3 rounded-lg py-3 px-5 bg-red-600 text-white ", method: :delete, data: {"turbo-method": :delete}%>
      </div>
    </div>
  </div>
<% end %>

app/views/menus/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Menus#create</h1>
  <p>Find me in app/views/menus/create.html.erb</p>
</div>

app/views/menus/destroy.html.erb
<div>
  <h1 class="font-bold text-4xl">Menus#destroy</h1>
  <p>Find me in app/views/menus/destroy.html.erb</p>
</div>

app/views/menus/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@menu) %>
<%= turbo_stream.update("toasts", partial: "shared/flash") %>

app/views/menus/edit.html.erb
<%= render partial: "shared/page_header", locals: {title: "Update your menu"} %>
<div class="shadow-md">
  <%= render "form" %>
  <div class="flex items-center justify-between">
    <div class="p-4 ml-2">
      <h3 class="text-lg font-medium leading-6 text-gray-900">Menu Sections</h3>
      <p class="mt-1 text-sm text-gray-500">Organize your menu with sections.</p>
    </div>
    <div class="mt-4 flex md:mt-0 mr-5">
      <%= link_to new_menu_section_path(@menu), class: "ml-3 px-4 py-3 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2", data: {turbo_frame: "modal"}, title: "Add Menu Section" do %>
        <%= content_tag(:span, :playlist_add, class: "material-symbols-outlined  text-gray-400") %>
      <% end %>
    </div>
  </div>
  <div id="menu-sections" data-controller="drag" data-drag-url="/menus/:menu_id/sections/:id/move" role="list" class="space-y-4 px-4">
    <%= render(SectionComponent.with_collection(@menu.sections.order(position: :asc)))%>
  </div>
</div>

app/views/menus/index.html.erb
<%= render partial: "shared/page_header", locals: {title: "Menus", subtitle: "A list of Menus in your account", path: new_menu_path, button: "Create"} %>
<div class="mt-8 flex flex-col">
  <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
      <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg">
        <table class="min-w-full divide-y divide-gray-300">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Name</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Restaurant</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Address</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">City</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">State</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Zipcode</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Published</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">QR Code</th>
              <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                <span class="sr-only">Edit</span>
              </th>
              <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                <span class="sr-only">Delete</span>
              </th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-200 bg-white">
            <% current_user.menus.each do |menu| %>
              <tr id="<%= dom_id(menu) %>">
                <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6">
                  <%= link_to menu.title, menu_path(menu), class: "text-indigo-600 hover:text-indigo-900", title: "View Menu"  %>
                </td>
                <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6">
                  <%= link_to menu.restaurant.name, edit_restaurant_path(menu.restaurant), class: "text-indigo-600 hover:text-indigo-900", title: "Download QR Code"  %>
                </td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= menu.restaurant.address %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= menu.restaurant.city %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= menu.restaurant.state %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= menu.restaurant.zipcode %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= human_boolean(menu.published?) %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                  <%= link_to "Download", qr_code_menu_path(menu), class: "text-indigo-600 hover:text-indigo-900", title: "Download QR Code"  %>
                </td>
                <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                  <%= link_to "Edit", edit_menu_path(menu), class: "text-indigo-600 hover:text-indigo-900", title: "Edit Menu"  %>
                </td>
                <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                  <%= link_to "Delete", confirm_menu_path(menu), class: "text-indigo-600 hover:text-indigo-900", data: {turbo_frame: "modal"}, title: "Delete Menu"  %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/menus/update.html.erb
<div>
  <h1 class="font-bold text-4xl">Menus#update</h1>
  <p>Find me in app/views/menus/update.html.erb</p>
</div>

app/views/menus/update.turbo_stream.erb
<%= turbo_stream.update("toasts", partial: "shared/flash") %>
<%= turbo_stream.update("errors", "") %>