config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :menus do
    get :confirm, on: :member
    get :qr_code, on: :member
    resources :sections do
      patch :move, on: :member
      get :confirm, on: :member
      resources :items do
        patch :move, on: :member
        get :confirm, on: :member
      end
    end
  end
  resources :restaurants do
    get :confirm, on: :member
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :site
  
  unauthenticated do
    root "site#index"
  end

  authenticated :user do
    root "menus#index", as: :authenticated_root
  end
end

app/views/shared/_confirm.html.erb
<dialog id="turbo-confirm" class="rounded shadow-md">
  <form method="dialog">
    <div class="px-4 py-5 border-b border-gray-200 sm:px-6">
      <h3 id="modal-title" class="text-lg leading-6 font-medium text-gray-900">Are you Sure?</h3>
    </div>
    <div>
      <button value="confirm">Yes</button>
      <button value="cancel">No</button>
    </div>
  </form>
</dialog>

app/views/shared/_dropdown_links.html.erb
<%= link_to "Your Profile", edit_user_registration_path, class: "nav-submenu", role: "menuitem", tabindex: "-1" %>
<%= button_to "Sign out", destroy_user_session_path, class: "nav-submenu", role: "menuitem", tabindex: "-1", method: :delete %>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div data-controller="flash" class="flex items-center <%= css_class_for_flash(key)  %> p-4 rounded-md fixed top-5 right-5">
    <%= value %>
    <button type="button" data-action="flash#dismiss">
      <%= heroicon "x-mark", options: { class: "ml-4" } %>
    </button>
  </div>
  <% flash.discard %>
<% end %>

app/views/shared/_form_errors.html.erb
<% if f.object.errors.any? %>
  <div id="errors" class="sm:col-span-4">
    <div class="rounded-md bg-red-50 p-4">
      <div class="flex">
        <div class="flex-shrink-0">
          <%= content_tag(:span, :cancel, class: "material-symbols-outlined  text-red-400") %>
        </div>
        <div class="ml-3">
          <h3 class="text-sm font-medium text-red-800">There was <%= pluralize(f.object.errors.count, "error") %> with your submission</h3>
          <div class="mt-2 text-sm text-red-700">
            <ul role="list" class="list-disc space-y-1 pl-5">
              <% f.object.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_mobile_dropdown_links.html.erb
<%= link_to "Your Profile", edit_user_registration_path, class: "nav-mobile-submenu" %>
<%= button_to "Sign out", destroy_user_session_path, class: "nav-mobile-submenu", method: :delete %>

app/views/shared/_mobile_nav_links.html.erb
<%= link_to "Menus", menus_path, class: [class_names(controller.controller_name == 'menus' ? 'nav-mobile-active' : 'nav-mobile-secondary'), "nav-mobile"] %>
<%= link_to "Restaurants", restaurants_path, class: [class_names(controller.controller_name == 'restaurants' ? 'nav-mobile-active' : 'nav-mobile-secondary'), "nav-mobile"] %>

app/views/shared/_nav.html.erb
<nav class="bg-gray-800">
  <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
    <div class="flex h-16 items-center justify-between">
      <div class="flex items-center">
        <div class="flex-shrink-0">
          <%= inline_svg_tag "logo.svg", class: 'h-9 w-9 stroke-white', alt: "Menu Maker" %>
        </div>
        <div class="hidden md:block">
          <div class="ml-10 flex items-baseline space-x-4">
            <%= render 'shared/nav_links' %>
          </div>
        </div>
      </div>
      <div class="hidden md:block">
        <div class="ml-4 flex items-center md:ml-6">
          <button type="button" class="rounded-full bg-gray-800 p-1 text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800">
            <span class="sr-only">View notifications</span>
            <!-- Heroicon name: outline/bell -->
            <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0" />
            </svg>
          </button>
          <!-- Profile dropdown -->
          <div class="relative ml-3">
            <div>
              <button x-on:click="menu = !menu" @click.away="menu = false" type="button" class="flex max-w-xs items-center rounded-full bg-gray-800 text-sm focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
                <span class="sr-only">Open user menu</span>
                <%= heroicon "user-circle", class: "text-gray-400", size: 24 %>
              </button>
            </div>
            <!--
                Dropdown menu, show/hide based on menu state.

                Entering: "transition ease-out duration-100"
                  From: "transform opacity-0 scale-95"
                  To: "transform opacity-100 scale-100"
                Leaving: "transition ease-in duration-75"
                  From: "transform opacity-100 scale-100"
                  To: "transform opacity-0 scale-95"
              -->
            <div x-show="menu" x-cloak class="absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1">
              <%= render 'shared/dropdown_links' %>
            </div>
          </div>
        </div>
      </div>
      <div class="-mr-2 flex md:hidden">
        <!-- Mobile menu button -->
        <button x-on:click="menu = !menu" type="button" class="inline-flex items-center justify-center rounded-md bg-gray-800 p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800" aria-controls="mobile-menu" aria-expanded="false">
          <span class="sr-only">Open main menu</span>
          <!--
              Heroicon name: outline/bars-3

              Menu open: "hidden", Menu closed: "block"
            -->
          <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
          <!--
              Heroicon name: outline/x-mark

              Menu open: "block", Menu closed: "hidden"
            -->
          <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
    </div>
  </div>
  <!-- Mobile menu, show/hide based on menu state. -->
  <div x-show="menu" @click.away="menu = false" x-cloak class="md:hidden" id="mobile-menu">
    <div class="space-y-1 px-2 pt-2 pb-3 sm:px-3">
      <%= render 'shared/mobile_nav_links' %>
    </div>
    <div class="border-t border-gray-700 pt-4 pb-3">
      <div class="flex items-center px-5">
        <div class="flex-shrink-0">
          <%= heroicon "user-circle", class: "text-gray-400", size: 34 %>
        </div>
        <div class="ml-3">
          <div class="text-base font-medium leading-none text-white"><%= current_user.first %> <%=current_user.last%></div>
          <div class="text-sm font-medium leading-none text-gray-400"><%= current_user.email%></div>
        </div>
        <button type="button" class="ml-auto flex-shrink-0 rounded-full bg-gray-800 p-1 text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800">
          <span class="sr-only">View notifications</span>
          <!-- Heroicon name: outline/bell -->
          <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0" />
          </svg>
        </button>
      </div>
      <div class="mt-3 space-y-1 px-2">
        <%= render 'shared/mobile_dropdown_links' %>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_nav_links.html.erb
<%= link_to "Menus", menus_path, class: [class_names(controller.controller_name == 'menus' ? 'nav-menu-active' : 'nav-menu-secondary'), "nav-menu"] %>
<%= link_to "Restaurants", restaurants_path, class: [class_names(controller.controller_name == 'restaurants' ? 'nav-menu-active' : 'nav-menu-secondary'), "nav-menu"] %>

app/views/shared/_page_header.html.erb
<div class="md:flex md:items-center md:justify-between">
  <div class="min-w-0 flex-1">
    <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:truncate sm:text-3xl sm:tracking-tight"><%= title %></h2>
    <% if defined?(subtitle) %>
      <div class="mt-2 flex items-center text-sm text-gray-500">
        <%= subtitle %>
      </div>
    <% end %>
  </div>
  <div class="mt-4 flex md:mt-0 md:ml-4">
    <% if defined?(button) && defined?(path) %>
      <%= link_to button, path, class: "ml-3 inline-flex items-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
    <%end%>
  </div>
</div>