config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :menus do
    get :confirm, on: :member
    get :qr_code, on: :member
    resources :sections do
      patch :move, on: :member
      get :confirm, on: :member
      resources :items do
        patch :move, on: :member
        get :confirm, on: :member
      end
    end
  end
  resources :restaurants do
    get :confirm, on: :member
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :site
  
  unauthenticated do
    root "site#index"
  end

  authenticated :user do
    root "menus#index", as: :authenticated_root
  end
end

app/models/section.rb
class Section < ApplicationRecord
  include Turbo::Streams::ActionHelper
  include Turbo::Streams::StreamName
  acts_as_list
  belongs_to :menu
  has_many :items, dependent: :destroy
  validates :title, presence: true
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_menu, only: [:create, :new, :edit, :update, :destroy, :confirm]
  before_action :set_section, only: [:move, :edit, :update, :destroy, :confirm]

  def new
    @section = Section.new(menu: @menu)
  end

  def create
    @section = Section.new(section_params)
    @section.menu = @menu

    if @section.save
      @section.insert_at(1)
      flash[:notice] = "Section Added."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @section.update(section_params)
      flash[:notice] = "Section Updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def move
    @section.insert_at(params[:position].to_i)
    respond_to do |format|
      flash[:notice] = "Section order was successfully updated."
      format.turbo_stream {
        render turbo_stream: [
          turbo_stream.update("toasts", partial: "shared/flash"),
        ]
      }
    end
  end

  def confirm
  end

  def destroy
    if @section.destroy
      flash[:notice] = "Section Removed."
    end
  end

  private

  def set_menu
    @menu = authorize Menu.find(params[:menu_id])
  end

  def set_section
    @section = authorize Section.find(params[:id])
  end

  def section_params
    params.require(:section).permit(:title, :description)
  end
end

app/views/sections/_form.html.erb
<%= form_with model: @section, url: [@menu, @section], builder: TailwindBuilder, class: "p-4" do |f| %>
  <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
    <%= render partial: 'shared/form_errors', locals: {f:f} %>
    <div class="sm:col-span-4">
      <%= f.label :title %>
      <%= f.tw_text_field :title, placeholder: "Appetizers", autocomplete: "off" %>
    </div>
    <div class="sm:col-span-4">
      <%= f.label :description %>
      <%= f.tw_text_area :description, placeholder: "Our Appetizers are the best", autocomplete: "off" %>
    </div>
    <div class="mt-4 p-5 flex justify-end">
      <%= button_tag "Close", data: { action: "modal#hideModal" }, type: "button", class: "rounded-lg py-3 px-5 bg-red-600 text-white" %>
      <%= f.submit "Save", class: "ml-3 inline-flex justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
    </div>
  </div>
<% end %>

app/views/sections/confirm.html.erb
<%= render TurboModalComponent.new(title: "Are you sure?") do %>
  <div class="mt-2 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
    <div class="sm:col-span-4">Do you really want to delete <%= @section.title %>?</div>
    <div class="sm:col-span-4">
      This will also delete the following menu items:
      <ul>
        <% @section.items.each do |i|%>
          <%= i.title %>
        <%end%>
      </ul>
    </div>
    <div class="sm:col-span-4">
      <div class="flex">
        <%= button_tag "Cancel", data: { action: "modal#hideModal" }, type: "button", class: "rounded-lg py-3 px-5 bg-blue-600 text-white" %>
        <%= button_to 'Delete', menu_section_path(@menu, @section), class: "ml-3 rounded-lg py-3 px-5 bg-red-600 text-white ", method: :delete, data: {"turbo-method": :delete}%>
      </div>
    </div>
  </div>
<% end %>

app/views/sections/create.turbo_stream.erb
<%= turbo_stream.prepend "menu-sections" do %>
  <%= render(SectionComponent.new(section: @section))%>
<% end %>
<%= turbo_stream.update("toasts", partial: "shared/flash") %>

app/views/sections/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@section) %>
<%= turbo_stream.update("toasts", partial: "shared/flash") %>

app/views/sections/edit.html.erb
<%= render TurboModalComponent.new(title: "Update Menu Section") do %>
  <%= render "form", section: @section %>
<% end %>

app/views/sections/new.html.erb
<%= render TurboModalComponent.new(title: "New Menu Section") do %>
  <%= render "form" %>
<% end %>

app/views/sections/update.turbo_stream.erb
<%= turbo_stream.replace dom_id(@section) do %>
  <%= render(SectionComponent.new(section: @section))%>
<% end %>
<%= turbo_stream.update("toasts", partial: "shared/flash") %>