config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :menus do
    get :confirm, on: :member
    get :qr_code, on: :member
    resources :sections do
      patch :move, on: :member
      get :confirm, on: :member
      resources :items do
        patch :move, on: :member
        get :confirm, on: :member
      end
    end
  end
  resources :restaurants do
    get :confirm, on: :member
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :site
  
  unauthenticated do
    root "site#index"
  end

  authenticated :user do
    root "menus#index", as: :authenticated_root
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user
  has_many :menus, dependent: :destroy
  has_one :active_menu, -> { where(menus: { published: true }) }, class_name: "Menu"
  has_many :business_hours, dependent: :destroy
  has_one_attached :image
  has_many :likes, as: :likeable, dependent: :destroy
  accepts_nested_attributes_for :business_hours, allow_destroy: true
  validates :name, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zipcode, presence: true
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_restaurant, only: [:edit, :update, :show, :destroy, :confirm]
  before_action :set_hours, only: [:new, :edit]

  def index
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user_id = current_user.id
    if @restaurant.valid?
      @restaurant.save
      redirect_to restaurants_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def new
    @restaurant = Restaurant.new
    Date::DAYS_INTO_WEEK.each_value do |i|
      @restaurant.business_hours.build
    end
  end

  def update
    if @restaurant.update(restaurant_params)
      @restaurant.save
      redirect_to restaurants_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def edit
  end

  def confirm
  end

  def destroy
    if @restaurant.destroy
      flash[:notice] = "Restaurant Removed."
    else
      flash[:notice] = "Unable to Remove Restaurant."
    end
  end

  private

  def set_restaurant
    @restaurant = authorize Restaurant.find(params[:id])
  end

  def set_hours
    @hours = [["12:00 AM", "00:00:00"],
              ["12:30 AM", "00:30:00"],
              ["1:00 AM", "01:00:00"],
              ["1:30 AM", "01:30:00"],
              ["2:00 AM", "02:00:00"],
              ["2:30 AM", "02:30:00"],
              ["3:00 AM", "03:00:00"],
              ["3:30 AM", "03:30:00"],
              ["4:00 AM", "04:00:00"],
              ["4:30 AM", "04:30:00"],
              ["5:00 AM", "05:00:00"],
              ["5:30 AM", "05:30:00"],
              ["6:00 AM", "06:00:00"],
              ["6:30 AM", "06:30:00"],
              ["7:00 AM", "07:00:00"],
              ["7:30 AM", "07:30:00"],
              ["8:00 AM", "08:00:00"],
              ["8:30 AM", "08:30:00"],
              ["9:00 AM", "09:00:00"],
              ["9:30 AM", "09:30:00"],
              ["10:00 AM", "10:00:00"],
              ["10:30 AM", "10:30:00"],
              ["11:00 AM", "11:00:00"],
              ["11:30 AM", "11:30:00"],
              ["12:00 PM", "12:00:00"],
              ["12:30 PM", "12:30:00"],
              ["1:00 PM", "13:00:00"],
              ["1:30 PM", "13:30:00"],
              ["2:00 PM", "14:00:00"],
              ["2:30 PM", "14:30:00"],
              ["3:00 PM", "15:00:00"],
              ["3:30 PM", "15:30:00"],
              ["4:00 PM", "16:00:00"],
              ["4:30 PM", "16:30:00"],
              ["5:00 PM", "17:00:00"],
              ["5:30 PM", "17:30:00"],
              ["6:00 PM", "18:00:00"],
              ["6:30 PM", "18:30:00"],
              ["7:00 PM", "19:00:00"],
              ["7:30 PM", "19:30:00"],
              ["8:00 PM", "20:00:00"],
              ["8:30 PM", "20:30:00"],
              ["9:00 PM", "21:00:00"],
              ["9:30 PM", "21:30:00"],
              ["10:00 PM", "22:00:00"],
              ["10:30 PM", "22:30:00"],
              ["11:00 PM", "23:00:00"],
              ["11:30 PM", "23:30:00"]]
  end

  def restaurant_params
    params.require(:restaurant).permit(
      :name, :address, :address2, :city, :state, :zipcode,
      :phone, :email, :web, :twitter, :instagram, :facebook,
      :image,
      business_hours_attributes: [:day, :open_at, :close_at, :closed, :id],
    )
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_for @restaurant, builder: TailwindBuilder do |f| %>
  <div class="shadow-md">
    <div class="mt-4 grid grid-cols-1 sm:grid-cols-2 mx-auto px-2 sm:divide-x divide-solid">
      <div class="p-4">
        <div>
          <h3 class="text-lg font-medium leading-6 text-gray-900">Business Information</h3>
          <p class="mt-1 text-sm text-gray-500">Use the valid information that customers can use to connect with you.</p>
        </div>
        <%= render partial: 'shared/form_errors', locals: {f:f} %>
        <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
          <div class="sm:col-span-4">
            <%= f.label :name, "Restaurant Name" %>
            <%= f.tw_text_field :name, required: true %>
          </div>
          <div class="sm:col-span-4">
            <%= f.label :address %>
            <%= f.tw_text_field :address, required: true %>
          </div>
          <div class="sm:col-span-4">
            <%= f.label :address2, "Address Continued" %>
            <%= f.tw_text_field :address2 %>
          </div>
          <div class="sm:col-start-1 sm:col-span-2">
            <%= f.label :city %>
            <%= f.tw_text_field :city, required: true %>
          </div>
          <div class="sm:col-span-2">
            <%= f.label :state %>
            <%= f.tw_text_field :state, required: true %>
          </div>
          <div class="sm:col-span-2">
            <%= f.label :zipcode %>
            <%= f.tw_text_field :zipcode, required: true %>
          </div>
          <div class="sm:col-span-4">
            <%= f.label :phone, "Phone Number" %>
            <%= f.tw_phone_field :phone %>
          </div>
          <div class="sm:col-span-4">
            <%= f.label :email, "Email Address" %>
            <%= f.tw_email_field :email %>
          </div>
          <div class="sm:col-span-4">
            <%= f.label :web, "Web Site" %>
            <%= f.site_field :web, {site: "https://"} %>
          </div>
          <div class="sm:col-span-4">
            <%= f.label :twitter %>
            <%= f.site_field :twitter, {site: "twitter.com/"} %>
          </div>
          <div class="sm:col-span-4">
            <%= f.label :instagram %>
            <%= f.site_field :instagram, {site: "instagram.com/"} %>
          </div>
          <div class="sm:col-span-4">
            <%= f.label :facebook %>
            <%= f.site_field :facebook, {site: "facebook.com/"} %>
          </div>
        </div>
      </div>
      <div class="p-4">
        <div>
          <h3 class="text-lg font-medium leading-6 text-gray-900">Business Hours</h3>
          <p class="mt-1 text-sm text-gray-500">Your regular operating hours of business.</p>
        </div>
        <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
          <%= f.fields_for :business_hours do |b| %>
            <%= b.hidden_field :day, value: b.index %>
            <div class="sm:col-span-5">
              <h3 class="font-medium leading-6 text-gray-900"><%= Date::DAYNAMES[b.index] %></h3>
            </div>
            <div class="-mt-4 sm:col-span-2">
              <%= b.label :open_at, "Open at", class: "block text-sm font-medium text-gray-700" %>
              <%= b.select :open_at, @hours, {class: "block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"} %>
            </div>
            <div class="-mt-4 sm:col-span-2">
              <%= b.label :close_at, "Close at", class: "block text-sm font-medium text-gray-700" %>
              <%= b.select :close_at, @hours, {class: "block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"} %>
            </div>
            <div class="-mt-4 sm:col-span-1 place-self-center">
              <%= b.check_box :closed, class: "h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500" %>
              <%= b.label :closed, class: "font-medium text-gray-700" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="mt-4 p-5 flex justify-end">
      <%= f.submit "Save", class: "ml-3 inline-flex justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
    </div>
  </div>
<% end %>

app/views/restaurants/confirm.html.erb
<%= render TurboModalComponent.new(title: "Are you sure?") do %>
  <div class="mt-2 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
    <div class="sm:col-span-4">Do you really want to delete:</div>
    <div class="sm:col-span-6">
      <h2 class="text-2xl text-gray-900"><%= @restaurant.name %></h2>
      <p><%= @restaurant.address %><%= @restaurant.address2 %></p>
      <p><%= @restaurant.city %> <%= @restaurant.state %>, <%= @restaurant.zipcode %></p>
    </div>
    <div class="sm:col-span-4">
      <div class="flex">
        <%= button_tag "Cancel", data: { action: "modal#hideModal" }, type: "button", class: "rounded-lg py-3 px-5 bg-blue-600 text-white" %>
        <%= button_to 'Delete', restaurant_path(@restaurant), class: "ml-3 rounded-lg py-3 px-5 bg-red-600 text-white ", method: :delete, data: {"turbo-method": :delete}%>
      </div>
    </div>
  </div>
<% end %>

app/views/restaurants/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Restaurants#create</h1>
  <p>Find me in app/views/restaurants/create.html.erb</p>
</div>

app/views/restaurants/destroy.html.erb
<div>
  <h1 class="font-bold text-4xl">Restaurants#destroy</h1>
  <p>Find me in app/views/restaurants/destroy.html.erb</p>
</div>

app/views/restaurants/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@restaurant) %>
<%= turbo_stream.update("toasts", partial: "shared/flash") %>

app/views/restaurants/edit.html.erb
<%= render partial: "shared/page_header", locals: {title: "Update your Restaurant"} %>
<%= render "form" %>

app/views/restaurants/index.html.erb
<%= render partial: "shared/page_header", locals: {title: "Restaurants", subtitle: "A list of Restaurants in your account", path: new_restaurant_path, button: "Create"} %>
<div class="mt-8 flex flex-col">
  <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
      <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg">
        <table class="min-w-full divide-y divide-gray-300">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Name</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Address</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">City</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">State</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Zipcode</th>
              <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                <span class="sr-only">Edit</span>
              </th>
              <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                <span class="sr-only">Delete</span>
              </th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-200 bg-white">
            <% current_user.restaurants.each do |restaurant| %>
              <tr id="<%= dom_id(restaurant) %>">
                <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6"><%= restaurant.name %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= restaurant.address %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= restaurant.city %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= restaurant.state %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= restaurant.zipcode %></td>
                <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                  <%= link_to "Edit", edit_restaurant_path(restaurant), class: "text-indigo-600 hover:text-indigo-900" %>
                </td>
                <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                  <%= link_to "Delete", confirm_restaurant_path(restaurant), class: "text-indigo-600 hover:text-indigo-900", data: {turbo_frame: "modal"}, title: "Delete Menu"  %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/restaurants/new.html.erb
<%= render partial: "shared/page_header", locals: {title: "Create a new Restaurant"} %>

<%= render "form" %>

app/views/restaurants/update.html.erb
<div>
  <h1 class="font-bold text-4xl">Restaurants#update</h1>
  <p>Find me in app/views/restaurants/update.html.erb</p>
</div>